/** Declaration file generated by dts-gen */

export = build_url;

declare function build_url(url: any, options: any): any;

declare namespace build_url {
    // Circular reference from build_url
    const buildUrl: any;

    const prototype: {
    };

    function noConflict(): any;

    namespace noConflict {
        const prototype: {
        };

    }

}

